### ISSUE TITLE
Send notification events for knob touch / release

### ISSUE THREAD

**Issue by git-moss** [electraone/firmware#16]
The controller should send out a notification sysex message when a user touches or releases one of the knobs.
This is escpecially necessary to record automation in touch automation mode in a DAW.

**Comment by electraone** [comment]
what parameters/data should such a callback have? I have some ideas, of course, but I would like to know what would work the best for you.

**Comment by git-moss** [comment]
I think 2 bytes are sufficient:
- Index of the knob (0-11)
- Touch state: 1 = Touched, 0 = Released

**Comment by electraone** [comment]
Implemented. The Id of the control is provided in the event notification too.
