### ISSUE TITLE
Setting of value labels

### ISSUE THREAD

**Issue by git-moss** [electraone/firmware#17]
Currently, a formatter (LUA function) can be set to format a value on the device.
For DAW support in contrast the formatter is normally provided by the DAW and a script developer already gets the finalized text. Therefore, it wouldbe helpful to have either a setter for the label in LUA or (preferred) extend the already existing element update sysex command with a value label.

**Comment by electraone** [comment]
SysEx API command and a Lua functions were added. See the documentation for details.
