### ISSUE TITLE
Group headers are not updated

### ISSUE THREAD

**Issue by git-moss** [electraone/firmware#27]
There seems to be no reaction to the sysex command in Firmware 3.1.

**Comment by electraone** [comment]
I tested group:setLabel() function and it seems to work fine. I took a look at the latest version of DrivenByMoss .eproj project file. I see that there is no lua in it. When I added the sgt() function to the project, the Bitwig extension started to update the group labels. Can you check from your end?

**Comment by git-moss** [comment]
You are absolutely right! I guess I did accidently only download the preset instead of the project.
Thanks for looking into it!
